### ISSUE TITLE
build on Mac OSX

### ISSUE THREAD

**Issue by guitorri** [DoUML/douml#67]
Hello!

I gave it a try to compile on OSX 10.8.4 with the latest Xcode and Command line tools.
I had to adjust the .pro files so that clang++ knows about c++11 features and the std:: lib to use. 
I have Qt 4.8.4 from source with qt3support, boost 1.53.0 and clang:

<pre>
~/git/douml $ clang++ -v
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin12.4.0
Thread model: posix
</pre>

Compilation started ok.
Next it the compilation stopped at the initialzation of some QList and QStringList., which I fixed.
So far these changes are sitting on this branch:
https://github.com/guitorri/douml/tree/osx

But now I'm stuck with errors like these:

<pre>
CustomWidgets/quickeditcontrollersetup.cpp:214:5: error: no matching member function for call to 'AddGetter'
    ADD_GETSET(BrowserClass, classController, columns.indexOf("name"), std::initializer_list<int>({Qt::DisplayRole,Qt::EditRole}),
    ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CustomWidgets/quickeditcontrollersetup.cpp:36:13: note: expanded from macro 'ADD_GETSET'
    HOLDER->AddGetter(ROW,ROLES, \
            ^
CustomWidgets/quickeditcontrollersetup.cpp:214:5: error: no matching member function for call to 'AddSetter'
    ADD_GETSET(BrowserClass, classController, columns.indexOf("name"), std::initializer_list<int>({Qt::DisplayRole,Qt::EditRole}),
    ^                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CustomWidgets/quickeditcontrollersetup.cpp:49:13: note: expanded from macro 'ADD_GETSET'
    HOLDER->AddSetter(ROW,ROLES, \
            ^

</pre>

The longer error version is here: https://gist.github.com/guitorri/5967834

Do you have any clue of where should I look next?

Regards,
Guilherme
