### ISSUE TITLE
[Patch] Cannot compile with gcc4.9

### ISSUE THREAD

**Issue by glixx** [DoUML/douml#80]
Errors:
1)
In file included from src/AdaptingTableModel.cpp:28:0:
src/../include/TableDataInterface.h:65:39: error: 'std::function' has not been declared
     virtual void SetSortFunction(std::function<bool(void*, void*)> func) = 0;
                                       ^
src/../include/TableDataInterface.h:65:47: error: expected ',' or '...' before '<' token
     virtual void SetSortFunction(std::function<bool(void*, void*)> func) = 0;
2)
FileOut.cpp: In member function 'void FileOut::quote(const QString&)':
FileOut.cpp:167:45: error: 'function' is not a member of 'std'
     static std::unordered_map <std::string, std::function<void()>> converter = {
                                             ^
FileOut.cpp:167:45: error: 'function' is not a member of 'std'
FileOut.cpp:167:64: error: template argument 2 is invalid
     static std::unordered_map <std::string, std::function<void()>> converter = {
                                                                ^
FileOut.cpp:167:64: error: template argument 5 is invalid
FileOut.cpp:167:65: error: expected unqualified-id before '>' token
     static std::unordered_map <std::string, std::function<void()>> converter = {
                                                                 ^
FileOut.cpp:166:9: warning: unused variable 'i' [-Wunused-variable]
     int i = 0;
         ^
FileOut.cpp:184:1: error: expected '}' at end of input
 }
 ^
FileOut.cpp: At global scope:
FileOut.cpp:164:36: warning: unused parameter 's' [-Wunused-parameter]
 void FileOut::quote(const QString &s)
                                    ^
Makefile:2198: recipe for target '../../bin/obj_release/gxmi2/FileOut.o' failed
